# docker run -dp 80:8000 -v /opt/project/config/.env:/usr/src/laravel/.env okukharenko/laravel
version: "2"
services:
    redis:
        image: redis
        ports:
        -   "6379:6379"
        volumes:
        -   /docker/host/redis:/data
    api:
        image: okukharenko/laravel
        ports:
        -   "80:8000"
        volumes:
        -  /opt/project/config/.env:/usr/src/laravel/.env
